/*
  # Create APS Reports Table

  ## Summary
  Creates a table to store AI Publisher Score reports generated by users.

  ## New Tables
  - `aps_reports`
    - `id` (uuid, primary key)
    - `url` (text) — the business website URL analyzed
    - `overall_score` (integer) — the overall AI Publisher Score (0–100)
    - `platform_scores` (jsonb) — per-platform scores: { openai, gemini, copilot, grok, perplexity }
    - `is_demo` (boolean) — whether the report used demo/fallback data
    - `generated_at` (timestamptz) — when the report was generated
    - `created_at` (timestamptz) — when the record was inserted

  ## Security
  - RLS enabled
  - Public insert allowed (anonymous users can save reports)
  - Public select allowed for reports (so users can view their report after generation)
  - No update or delete policies (reports are immutable)
*/

CREATE TABLE IF NOT EXISTS aps_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  url text NOT NULL,
  overall_score integer NOT NULL DEFAULT 0,
  platform_scores jsonb NOT NULL DEFAULT '{}',
  is_demo boolean NOT NULL DEFAULT false,
  generated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE aps_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can insert a report"
  ON aps_reports
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "Anyone can read reports"
  ON aps_reports
  FOR SELECT
  TO anon, authenticated
  USING (true);
